### ISSUE TITLE
Webpack causes conflicts with other packages.

### ISSUE THREAD

**Issue by rolando-valdivia-incontact** [CLantigua2/react-dynamic-time-slider#2]
**Describe the bug**
When using this module with apps created with create-react-app, the command npm run build fails because react scripts depends on a lower version of webpack.

**To Reproduce**
1. create a new app with create-react-app.
2. Install this module with npm.
3. Add the module to a react component.
4. Run npm run build

**Expected behavior**
The build command finish without errors

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS

**Additional context**
create-react-app depends on a specific version of webpack, this module has webpack listed as a dependency instead of a devDependency. You need to move webpack to the devDependency section to avoid the described problem.

**Comment by CLantigua2** [comment]
hey @rolando-valdivia-incontact thanks a lot for reporting this. I've moved it down to devDependencies which should resolve the issue and republished the package. Thanks again.
